### ISSUE TITLE
Giant TODO list

### ISSUE THREAD

**Issue by dougthor42** [dougthor42/trendlines#3]
+ [ ] Tests. Lots of tests. All of the tests.
+ [ ] `/api/v1/<metric>`, `/api/v1/get/<metric>` to get JSON data for the given metric
+ [ ] accept UDP data
+ [ ] Dynamic, collapsing front page
+ [ ] Button to change between series and time-based data on `plot.html`
+ [ ] rename `routes.get_data` because it's too easy to get confused with `db.get_data`. I spent over an hour debugging something because of that...
+ [ ] Docker container
+ [ ] Update "Usage" section in `README.md`
+ [ ] CI
+ [ ] Able to easily go back to the main page, or able to see other related graphs (ie: easy to get from `foo.bar.baz` to `foo.bar.zen`
+ [ ] Multiple plots per page - easy to compare things vs time.
+ [ ] Add the namesake: some trendlines. Simple linear extrapolation based on N historical points. (not really important, in my opinion...)
+ [ ] Simple alerting system: email when out trend falls out of spec.
